workflows:
    version: 2
    build:
        jobs:
            - build_node_6
            - build_node_8

version: 2
jobs:
    base: &base
        working_directory: ~/workspace
        docker:
            - image: circleci/node:6.11
        steps:
            - checkout
            - restore_cache:
                key: add-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}
            - run: git submodule update --init
            - run:
                name: Install dependencies
                command: npm i --registry https://registry.npmjs.org
            - run:
                name: Build samples
                command: ./build-samples.sh
            - save_cache:
                key: add-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}
                paths:
                    - "node_modules"

    build_node_6:
        <<: *base
        docker:
        - image: circleci/node:6.11

    build_node_8:
        <<: *base
        docker:
        - image: circleci/node:8.9
